### ISSUE TITLE
There is a Bluetooth driver for Intel to release. Can you tell me if I can drive it

### ISSUE THREAD

**Issue by cykzht** [daliansky/XiaoMi-Pro-Hackintosh#323] opened 2020-01-03 15:24 UTC
On the first day of 2020, a engineer released the Intel Bluetooth driver, which can be driven by a cold start. The website is https://github.com/zxystd/IntelBluetoothFirmware
I put the driver into kexts, but it doesn't work, and even there is no blue tooth option in the settings. I want to know 
1. Is EFI shielding Intel Bluetooth? If so, how can I solve it Except him
2. Can the engineer's driver be added to future EFI files
The version I am using is released Xiaomi notebook Pro EFI v1.3.5
Please solve it. Thank you very much.

**Comment by Menchen** [comment] 2020-01-03 15:26
The link is broken or repo is deleted...

**Comment by cykzht** [comment] 2020-01-03 15:29
Sorry, this is my error, the link has been updated
https://github.com/zxystd/IntelBluetoothFirmware

**Comment by Menchen** [comment] 2020-01-03 15:51
@cykzht I have tried it and it works fine, so how did you installed it? And can you update your EFI with `bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"`? make sure to choose the default in the Bluetooth option.

**Comment by cykzht** [comment] 2020-01-04 01:26
@Menchen I tried to update the EFI file and select the Bluetooth option as the default, but I still cannot find the Bluetooth option in the settings, and there is no Bluetooth information in the system information

**Comment by zrx0** [comment] 2020-01-04 01:27
> @cykzht I have tried it and it works fine, so how did you installed it? And can you update your EFI with `bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)"`? make sure to choose the default in the Bluetooth option.
> 
> EDIT: Make sure that you are running mojave.

Thank you for reference to the bluetooth. I will try it today, but before will try, I'm running Mojave at this moment. I'm thinking to upgrade to Catalina. As I see your comment it's working in Mojave, what about Catalina?

**Comment by Menchen** [comment] 2020-01-04 03:13
@zrx0 sorry I meant Catalina.... If you want it to rub in Mojave you need manually edit dependency and rebuild it. Make sure that you have Bluetooth in settings before you install.

**Comment by Menchen** [comment] 2020-01-04 03:16
@cykzht then try a full EFI reinstalls... download directly from repo and delete OC folders before rebooting.

**Comment by cykzht** [comment] 2020-01-04 15:06
@Menchen Thank you for your reply. Now I have successfully driven Bluetooth. The problem is on SSDT-USB.aml. You can use my SSDT file, [Download links](https://cykrldzp.goho.co:85/wp-content/uploads/2020/01/SSDT-USB.aml)
At the same time, it should be noted that this driver is based on the 10.15 system. If you are 10.14, you can refer to the 10.14 version compiled by this master. [#7](https://github.com/zxystd/IntelBluetoothFirmware/issues/7#issuecomment-570451673)
Once again, thank you for helping me solve the problem. You can share my experience with others so that they can better use the Bluetooth service.

**Comment by zrx0** [comment] 2020-01-04 18:18
> @zrx0 sorry I meant Catalina.... If you want it to rub in Mojave you need manually edit dependency and rebuild it. Make sure that you have Bluetooth in settings before you install.

Thanks for the reply, I upgraded to Catalina on the Xiaomi mi air 13"2019. I got the bluetooth working as far I see, but a bit laggy not always working, some of the bluetooth devices doesn't connect with it. Unfortunately I got two problems with installing (upgrade to) the Catalina, my touchpad doesn't work anymore, not even when I updated the kext. Try to install the old kext on it, but even with that not working. Also my brightness buttons (doesn't work, so I'm thinking to go back to Mojava). Seems Catalina is not stable enough on the Xiaomi mi air 13. Don't know about the 15 'Pro' version.  Any one have solution?

**Comment by Menchen** [comment] 2020-01-04 18:22
@zrx0 Catalina is stable enough.. I think the problem is your Kext(both Kext need be adjusted to your device, copy directly from this repo won’t help). Everything work fine in pro version.

**Comment by zrx0** [comment] 2020-01-04 18:30
> @zrx0 Catalina is stable enough.. I think the problem is your Kext(both Kext need be adjusted to your device, copy directly from this repo won’t help). Everything work fine in pro version.

Yes I adjust them, I've been busy with it, but didn't work out well, but just got them working right now. Everything is now working fine. Only thing need to do is fixing the wifi and it's 1:1 all most with a Macbook. Thank you! :)

**Comment by johnnync13** [comment] 2020-01-05 08:42
@cykzht https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v4.5

**Comment by jackreeves** [comment] 2020-01-05 13:24
hey all. i just quickly tried to get this to install but realised i never got around to upgrading to catalina! last day of my vacation so downloading now to take care of it today. im on a 15" 8550 w/ 16gb. It seems like these kexts will help me have an even more native machine (although thanks menchen for the VM work). For catalina on a fresh EFI are these the steps i need to take?

1. Download v 1.0.1 from https://github.com/zxystd/IntelBluetoothFirmware/releases
2. Mount EFI using Clover Configurator
3. Ensure using latest release EFI From https://github.com/daliansky/XiaoMi-Pro-Hackintosh/releases
4. Add both IntelBluetoothFirmware.kext and IntelBluetoothInjector.kext to /EFI/CLOVER/Kext/Other
5. Rebuild kext using terminal command `sudo kextcache -i /`
6. Shutdown
7. Power on

Anything missing? @johnnync13 @zrx0 @Menchen ?

**Comment by Menchen** [comment] 2020-01-05 13:33
First of all thanks for your supporting, and in steps 3 I would recommend using EFI directly from repo in code tab under EFI folder, and delete OC folders. Also you need rebuild cache after reboot so new Kext is loaded.

One more things is to remove launch agents  script that you used to auto start VMWare.

**Comment by zrx0** [comment] 2020-01-06 18:40
> @zrx0
> https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v4.5

Thank you, I'm at this moment using the current one above. It works oke, not perfect. Gonna try this one out, once again. Thank you :-)

**Comment by zrx0** [comment] 2020-01-06 18:41
> @zrx0
> https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v4.5

Thank you, will check this out! :-)

**Comment by cykzht** [comment] 2020-01-07 14:27
Hello everyone, I'm the author. Here's a video about the driver installation. If it's helpful to you, please view [bilibili](https://www.bilibili.com/video/av82455447)

**Comment by jackreeves** [comment] 2020-01-08 12:13
thanks everyone. install went to plan on both mine and the wifes machines. thanks @cykzht for helping us get almost all the way to a native machine and thanks @Menchen for everything on top!

every now and again i do notice an ever so slight slow down of the mouse tracking speed when doing heavy design work on mine. but not sure if that is catalina as updated both at same time.

**Comment by idears-org** [comment] 2020-01-16 05:53
Hi @stevezhengshiqi @daliansky Is it possible to add native bluetooth support to this project use the method mentioned above?

**Comment by Cr0wTom** [comment] 2020-01-16 12:58
Should we consider this https://github.com/zxystd/AppleIntelWifiAdapter as a WIP for onboard WiFi? :O It's the same guy.

**Comment by stevezhengshiqi** [comment] 2020-01-16 21:29
@idears-org Currently I have no device to start a test. By the way, thank you all for this great Intel Bluetooth solution!👍👍👍 I will add the support as soon as the solution has been fully tested. Special thanks to @cykzht

**Comment by ZambraDesigner** [comment] 2020-01-20 21:22
@stevezhengshiqi After stopping the bluetooth no longer works..can it be solved?

**Comment by stevezhengshiqi** [comment] 2020-01-20 23:17
@ZambraDesigner I haven't reviewed the code of IntelBluetoothFirmware yet. You can go to https://github.com/zxystd/IntelBluetoothFirmware/issues for professional support.

**Comment by Drun555** [comment] 2020-02-03 09:53
@ZambraDesigner Can we copy /master for testing for now? Seems like you added kext for awhile.

**Comment by clmsftsw** [comment] 2020-02-04 15:59
> 
> 
> hey all. i just quickly tried to get this to install but realised i never got around to upgrading to catalina! last day of my vacation so downloading now to take care of it today. im on a 15" 8550 w/ 16gb. It seems like these kexts will help me have an even more native machine (although thanks menchen for the VM work). For catalina on a fresh EFI are these the steps i need to take?
> 
> **UPDATED TO REFLECT WORKING STEPS**
> 
>     1. Download v 1.0.1 from https://github.com/zxystd/IntelBluetoothFirmware/releases
> 
>     2. Mount EFI using Clover Configurator
> 
>     3. Ensure using latest  ̶r̶e̶l̶e̶a̶s̶e̶ ̶E̶F̶I̶ ̶F̶r̶o̶m̶ ̶h̶t̶t̶p̶s̶:̶/̶/̶g̶i̶t̶h̶u̶b̶.̶c̶o̶m̶/̶d̶a̶l̶i̶a̶n̶s̶k̶y̶/̶X̶i̶a̶o̶M̶i̶-̶P̶r̶o̶-̶H̶a̶c̶k̶i̶n̶t̶o̶s̶h̶/̶r̶e̶l̶e̶a̶s̶e̶s̶ latest EFI at https://github.com/daliansky/XiaoMi-Pro-Hackintosh and deleted OC folder.
> 
>     4. Add both IntelBluetoothFirmware.kext and IntelBluetoothInjector.kext to /EFI/CLOVER/Kext/Other
> 
>     5. Remove startup script id installed for booting drivers via VMware
> 
>     6. Rebuild kext using terminal command `sudo kextcache -i /`
> 
>     7. Shutdown not restart and wait for 10 sec, Power on
> 
>     8. Rebuild kext using terminal command `sudo kextcache -i /`
> 
>     9. Shutdown not restart and wait for 10 sec, Power on

Can someone explain 5. ? I am new to hackintosh an I don't know what vmware is..

**Comment by jackreeves** [comment] 2020-02-04 16:08
That is if you used menchens previous method to get the internal bt
working. Please skip if you haven't installed that already.

**Comment by paajake** [comment] 2020-02-04 16:12
You can safely ignore if you don't know what it is. There was another way of getting bluetooth to work using a virtual machine image which required a vmware to mount, as can be seen here #262

**Comment by clmsftsw** [comment] 2020-02-04 19:30
Thank you. Do I need Catalina for it to function? And if yes how do I update? Do I have to update the kexte or clover? I am currently on Mojave and installed the latest EFI with the terminal command.

**Comment by paajake** [comment] 2020-02-04 20:39
I'm currently on Catalina (10.15.2), I've only tested it here, and it works.

To update, just update your EFI using the bash command in the README and use the mac **Software Update** in the **System Preferences**.  Make sure to select the mac installation in the boot menu on reboot till it completes.

**Comment by clmsftsw** [comment] 2020-02-04 22:43
Okay I could install Catalina without a problem and installed the kexts for bluetooth. It seems to work but unfortunatly I still can't connect my bluetooth mouse and keyboard (MX Master and Keys), altough I can see them in the bluetooth options.

**Comment by paajake** [comment] 2020-02-05 08:08
There seems to be a general issue with mac or hackingtosh and other Bluetooth mouse, I also can get my mi mouse to work.

**Comment by zrx0** [comment] 2020-02-05 21:31
> Okay I could install Catalina without a problem and installed the kexts for bluetooth. It seems to work but unfortunatly I still can't connect my bluetooth mouse and keyboard (MX Master and Keys), altough I can see them in the bluetooth options.

Same problem here, can't use the MX Master 3

**Comment by matvada** [comment] 2020-02-17 17:53
Hello everyone, after about a month of using this system I noticed a huge consumption of battery in bluetooth devices such as magic mouse and magic keyboard (both model 1 with alkaline batteries). With the previous method based on VMware the battery lasts much longer. 
Has anyone encountered the same problem?
Thanks

**Comment by jackreeves** [comment] 2020-02-17 17:59
Yeah I keep going through a set every two weeks. But I think this also
happened with the VM. I didn't get it with external adapter for sure.

**Comment by xiangjb1** [comment] 2020-03-04 03:26
This version only works properly on macos10.15

**Comment by CamilloCorleone** [comment] 2020-03-06 13:54
> > Okay I could install Catalina without a problem and installed the kexts for bluetooth. It seems to work but unfortunatly I still can't connect my bluetooth mouse and keyboard (MX Master and Keys), altough I can see them in the bluetooth options.
> 
> Same problem here, can't use the MX Master 3

Did you find a way to make MX Master work?

**Comment by clmsftsw** [comment] 2020-03-08 14:41
@CamilloCorleone No unfortunately I didn't. I ended up using the Unifying adapter. Now all my usb ports are occupied..

**Comment by stevezhengshiqi** [comment] 2020-03-17 16:22
Merged the IntelBluetooth driver into EFI v1.3.6. If the device sleeps with KP, please remove the kext.

**Closed by stevezhengshiqi** 2020-03-17 16:22 UTC
Labels: Bluetooth
