### ISSUE TITLE
Commit b7ec101 leads to black screen.

### ISSUE THREAD

**Issue by cook1e0** [daliansky/XiaoMi-Pro-Hackintosh#429] opened 2020-07-20 15:05 UTC
The latest commit leads to black screen once applying those changes:

```
<key>AAPL,ig-platform-id</key>
<data>CQCbPg==</data>
<key>device-id</key>
<data>mz4AAA==</data>
```

Second monitor still works, only the laptop screen is affected.
I have tried disabling HiDPI, still the same result. Can anyone else confirm this?

**Comment by stevezhengshiqi** [comment] 2020-07-20 17:31
Hi, what about removing the following line:
```
<key>framebuffer-con0-enable</key>
<data>AQAAAA==</data>
<key>framebuffer-con0-flags</key>
<data>mAQAAA==</data>
```

I don't have the chance to test it on my device. The idea of changing the `ig-platform-id` is from the group chat and I am sorry that it causes some problems.

**Comment by cook1e0** [comment] 2020-07-20 17:35
> I am sorry that it causes some problems.
No worries, we're all here to test, appreciate your work. 
Will try later removing that part later.

**Comment by cook1e0** [comment] 2020-07-20 17:53
Have removed this part from the config,

```
<key>framebuffer-con0-enable</key>
<data>AQAAAA==</data>
<key>framebuffer-con0-flags</key>
<data>mAQAAA==</data>
``` 

Black screen is resolved, although these 4 changes break the brightness control for the integrated display. Other than that, couldn't experience any improvements.

**Comment by recre4te** [comment] 2020-07-20 18:23
Hi, I had the same problem.
Also, on recommendation, I replaced this field with framebuffer-flags to CwfjAA == and this led to a worse picture, what is it for and how to make this flag work?

**Comment by stevezhengshiqi** [comment] 2020-07-20 19:16
Em weird. Some friends in the group chat say that the following configuration is better for 4K external monitors.
![Screen Shot 2020-07-21 at 03 15 01](https://user-images.githubusercontent.com/36894554/87976982-8f218a80-cb00-11ea-8622-52e5196c33f6.jpg)

**Comment by stevezhengshiqi** [comment] 2020-07-20 19:44
@recre4te 

> Also, on recommendation, I replaced this field with framebuffer-flags to CwfjAA ==  and this led to a worse picture, what is it for and how to make this flag work?

The difference between `CwfjAA==` and the original `CwfDAA==` is that the former one enables `FBEnableDynamicCDCLK`, which is required when enabling HiDPI resolution >= 1440x810. However, it breaks hibernatemode 25 wake up (https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/406), so I use the later one for default. Currently, there are no solutions for the glitches or blur image caused by `FBEnableDynamicCDCLK`, as 1080p screen is unwelcome on macOS.

**Comment by stevezhengshiqi** [comment] 2020-07-21 03:07
Fixed in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/commit/a33928425145874dc04d57cc7be3ee35b8348160

**Closed by stevezhengshiqi** 2020-07-21 03:07 UTC
Labels: Graphics
